language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npx prettier --check .
  - react-scripts build
install: true

branches:
  only:
    - master
